# Generated by Django 2.2.5 on 2019-10-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0005_auto_20191002_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, help_text='вопросы в тесте', to='recruiting.TestQuestions'),
        ),
    ]
