# Generated by Django 2.2.5 on 2019-10-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0008_auto_20191010_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='shadow_hand_rank',
            field=models.BooleanField(default=False, verbose_name='Наличие звания Руки Тени'),
        ),
    ]
