# Generated by Django 2.2.5 on 2019-09-24 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите наименование планеты', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя', max_length=50)),
                ('planet', models.ForeignKey(help_text='Планета, на которой вы обучаете', on_delete=django.db.models.deletion.PROTECT, to='recruiting.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя', max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(error_messages={'unique': 'Данный E-Mail уже зарегистрирован.'}, help_text='Введите email', max_length=50, unique=True)),
                ('shadow_hand_rank', models.BooleanField(default=False, verbose_name='Наличие звания Руки Тени')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruiting.Sith')),
                ('planet', models.ForeignKey(help_text='Планета, на которой вы обитаете', on_delete=django.db.models.deletion.PROTECT, to='recruiting.Planet')),
            ],
        ),
    ]
