# Generated by Django 2.2.5 on 2019-09-30 11:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный код испытания', primary_key=True, serialize=False)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.Recruit')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Введите текст вопроса', max_length=300)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.Test')),
            ],
        ),
        migrations.CreateModel(
            name='TestAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.Test')),
                ('to_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.TestQuestions')),
            ],
        ),
    ]
