# Generated by Django 2.2.5 on 2019-09-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0002_test_testanswers_testquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestions',
            name='is_used_in_test',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
