# Generated by Django 2.2.5 on 2019-09-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0003_testquestions_is_used_in_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestions',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(help_text='вопросы в тесте', to='recruiting.TestQuestions'),
        ),
        migrations.AlterField(
            model_name='testquestions',
            name='is_used_in_test',
            field=models.BooleanField(blank=True, default=False, help_text='Отметьте, чтобы использовать в тестах', verbose_name='Использовать в тестах'),
        ),
    ]
