# Generated by Django 2.2.5 on 2019-10-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0004_auto_20190930_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestions',
            name='is_used_in_test',
            field=models.BooleanField(blank=True, default=False, help_text='Отметьте, чтобы использовать вопрос в тестах', verbose_name='Использовать в тестах'),
        ),
    ]
